@startuml
class MovementOculusTouchRegulator {
    Start() : void
    Update() : void
}
MonoBehaviour <|-- MovementOculusTouchRegulator
MovementOculusTouchRegulator --> "RightOculusTouch" GameObject
@enduml
