@startuml
class SplashScreenButtonEvents {
    Start() : void
    ChangeState() : void
    SceneLoaderWithLoadingBar() : IEnumerator
}
MonoBehaviour <|-- SplashScreenButtonEvents
SplashScreenButtonEvents --> "LoadingObj" Text
@enduml
