@startuml
class VirtualMeter {
    Start() : void
    + {static} CalculateHeadingFromPositions(Pos1:Vector3, Pos2:Vector3) : float
    + {static} CalculateHeading(DirectionVector:Vector3) : float
    + {static} CalculateInclinationFromPositions(Pos1:Vector3, Pos2:Vector3) : float
    + {static} CalculateInclination(DirectionVector:Vector3) : float
    + {static} CalculateRealPositionOfPoint(point:Vector3) : Vector3Decimal
    + {static} CalculateGPSPosition(point:Vector3) : Vector3Decimal
    + {static} CalculateRealDistance(point1:Vector3, point2:Vector3) : decimal
    + {static} CalculateRealDistance2D(point1:Vector3, point2:Vector3) : decimal
    + {static} CalculateRealDistance(point1:Vector3Decimal, point2:Vector3Decimal) : decimal
    + {static} CalculateGroundDistance(start:Vector3, end:Vector3, lineRenderer:LineRenderer, maxRays:int) : decimal
    + {static} CalculateVerticalRealDistance2D(point1:Vector3, point2:Vector3) : decimal
    + {static} SetStaticGPSLatLonAltBox(_west_dd:Decimal, _east_dd:Decimal, _south_dd:Decimal, _north_dd:Decimal, _west_uu:Decimal, _east_uu:Decimal, _south_uu:Decimal, _north_uu:Decimal, _alt_min_dd:Decimal, _alt_max_dd:Decimal, _alt_min_uu:Decimal, _alt_max_uu:Decimal, _offset_alt:Decimal) : void
}
MonoBehaviour <|-- VirtualMeter
VirtualMeter --> "WalkingMasterObject" GameObject
VirtualMeter --> "FlyingMasterObject" GameObject
VirtualMeter --> "DroneMasterObject" GameObject
@enduml
